spring:
  main:
    banner-mode: console
  thymeleaf:
    cache: true
#    cache: false

server:
  port: 8000
logging:
  level:
    org.thymeleaf: TRACE
  file:
    #path: F:\common\temp             default file name: spring.log
    name: F:\common\temp\reading-list-log.log
